variables:
  AWS_REGION: ap-southeast-2
  AWS_ACCOUNT: 814504268053
  TF_VAR_app_env: Prod
  TF_VAR_recaptcha_site_key: 6LcmfrgUAAAAAILAIF_PlQWjPEPJi403Pv7GSK8T
  TF_VAR_stripe_publishable_key: pk_test_51HTJBRGZtHTgMn6lixC56XtF9cJiB8aVYwOlo3ycQfn72eNLI4hj4Zg3vsrDFjeX8mPz25HXG1z1gjhENIZfXFIC00VtpLKwW2
  TF_VAR_phishtank_username: stoff

before_script:
  - touch .env
  - make --version
  - terraform --version
  - aws --version
  - docker --version

stages:
  - plan
  - apply

tf:plan:
  retry: 2
  tags:
    - linode
  stage: plan
  script:
    - make plan
  only:
    refs:
      - merge_request
      - main
  artifacts:
    name: tfplan
    paths:
      - plans/.tfplan
    reports:
      terraform: plans/tfplan.json

tf:apply:
  retry: 2
  tags:
    - linode
  stage: apply
  script:
    - make apply
  only:
    refs:
      - main
  environment:
    name: aws
    url: https://sso.jumpcloud.com/saml2/aws1
    on_stop: tf:destroy
  dependencies:
    - tf:plan
  when: manual

tf:destroy:
  retry: 2
  stage: apply
  variables:
    GIT_STRATEGY: none
  tags:
    - linode
  script:
    - make destroy
  when: manual
  environment:
    name: aws
    action: stop
  artifacts:
    name: tfdestroy
    paths:
      - plans/.tfdestroy
    reports:
      terraform: plans/tfdestroy.json
