version: '3.9'
x-defaults: &defaults
  env_file: .env
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  linode-slackbot:
    <<: *defaults
    image: chrisdlangton/linode-slackbot
    environment:
      - LINODE_TOKEN=${LINODE_TOKEN}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    volumes:
      - db:/srv/app/sqlite
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.20'
          memory: 200M

  statping:
    <<: *defaults
    image: statping/statping
    container_name: statping
    volumes:
      - /root/statping:/app
    environment:
      NAME: Trivial Security
      DB_CONN: sqlite
      VIRTUAL_HOST: status.trivialsec.com
      VIRTUAL_PORT: 8080
      DOMAIN: https://status.trivialsec.com
      ADMIN_USER: admin
      ADMIN_PASSWORD: KVgu!J7uGC%wu6G3f6tjRvErViPWom&V
      ADMIN_EMAIL: support@trivialsec.com
    expose:
      - 8080
    networks:
      default:
        aliases:
          - statping
          - status
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  ghost:
    <<: *defaults
    image: ghost:4-alpine
    container_name: ghost
    volumes:
      - /root/ghost:/var/lib/ghost/content
    environment:
      url: https://www.langton.cloud
    expose:
      - 2368
    networks:
      default:
        aliases:
          - ghost
          - blog
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

  nginx:
    <<: *defaults
    image: nginx
    container_name: nginx
    volumes:
      - /root/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/certs:/etc/nginx/certs
      - /root/nginx/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf
      - /root/nginx/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  docs:
    <<: *defaults
    image: ghost:4-alpine
    container_name: docs
    volumes:
      - /root/docs:/var/lib/ghost/content
    environment:
      url: https://docs.trivialsec.com
    expose:
      - 2368
    networks:
      default:
        aliases:
          - docs
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 200M

volumes:
  db:
    external: true
    name: linode-slack-db

networks:
  default:
    external:
      name: containers
