version: '3.7'
x-defaults: &defaults
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  linode-slackbot:
    <<: *defaults
    image: chrisdlangton/linode-slackbot
    environment:
      - LINODE_TOKEN=${LINODE_TOKEN}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    volumes:
      - db:/srv/app/sqlite

  statping:
    <<: *defaults
    image: statping/statping
    container_name: statping
    volumes:
      - /root/statping:/app
    environment:
      NAME: Trivial Security
      DB_CONN: sqlite
      VIRTUAL_HOST: status.trivialsec.com
      VIRTUAL_PORT: 8080
      DOMAIN: https://status.trivialsec.com
      ADMIN_USER: admin
      ADMIN_PASSWORD: KVgu!J7uGC%wu6G3f6tjRvErViPWom&V
      ADMIN_EMAIL: support@trivialsec.com
    expose:
      - 8080
    networks:
      default:
        aliases:
          - statping
          - status

  ghost:
    <<: *defaults
    image: ghost:4-alpine
    container_name: ghost
    volumes:
      - /root/ghost:/var/lib/ghost/content
    environment:
      url: https://www.langton.cloud
    expose:
      - 2368
    networks:
      default:
        aliases:
          - ghost
          - blog

  nginx:
    <<: *defaults
    image: nginx
    container_name: nginx
    volumes:
      - /root/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - /root/letsencrypt/conf:/etc/letsencrypt
      - /root/letsencrypt/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 10m & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
      - NET_BIND_SERVICE

  certbot:
    <<: *defaults
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /root/letsencrypt/conf:/etc/letsencrypt
      - /root/letsencrypt/www:/var/www/certbot
    entrypoint: '/bin/sh -c ''trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'''
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  gitlab-runner:
    <<: *defaults
    image: registry.gitlab.com/trivialsec/containers-common/gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/gitlab-cache:/cache:rw
      - /root/gitlab-runner-config:/etc/gitlab-runner:rw

  docs:
    <<: *defaults
    image: ghost:4-alpine
    container_name: docs
    volumes:
      - /root/docs:/var/lib/ghost/content
    environment:
      url: https://docs.trivialsec.com
    expose:
      - 2368
    networks:
      default:
        aliases:
          - docs

volumes:
  db:
    external: true
    name: linode-slack-db
  gitlab-cache:
    external: true
    name: gitlab-cache

networks:
  default:
    external:
      name: containers
