---

amass:
  output_directory: /tmp
  maximum_dns_queries: 20000
  public_dns_resolvers: true
  score_resolvers: true
  monitor_resolver_rate: true
  bruteforce:
    enabled: true
    wordlist_file: /srv/app/lib/wordlists/all.txt
  alterations:
    enabled: false
    add_numbers: true
  sources_minimum_ttl: 1440
  sources:
    anubis:
      name: Anubis
      disabled: false
      ttl: 10080
    alienvault:
      name: AlienVault
      disabled: false
      ttl: 10080
    archivetoday:
      name: ArchiveToday
      disabled: false
      ttl: 10080
    ask:
      name: Ask
      disabled: true
    baidu:
      name: Baidu
      disabled: true
    binaryedge:
      name: BinaryEdge
      disabled: false
      ttl: 10080
    bgpview:
      name: BGPView
      disabled: false
      ttl: 10080
    bufferover:
      name: BufferOver
      disabled: false
      ttl: 10080
    builtwith:
      name: BuiltWith
      disabled: false
      ttl: 10080
    c99:
      name: C99
      disabled: false
      ttl: 4320
    commoncrawl:
      name: CommonCrawl
      disabled: false
      ttl: 4320
    censys:
      name: Censys
      disabled: false
      ttl: 10080
    certspotter:
      name: CertSpotter
      disabled: false
      ttl: 10080
    chaos:
      name: Chaos
      disabled: false
      ttl: 4320
    cloudflare:
      name: Cloudflare
      disabled: false
    circl:
      name: CIRCL
      disabled: false
      ttl: 10080
    dnsdb:
      name: DNSDB
      disabled: false
      ttl: 10080
    dnstable:
      name: DNSTable
      disabled: false
      ttl: 4320
    facebookct:
      name: FacebookCT
      disabled: false
      ttl: 4320
    github:
      name: GitHub
      disabled: false
      ttl: 4320
    hackerone:
      name: HackerOne
      disabled: false
      ttl: 4320
    hackertarget:
      name: HackerTarget
      disabled: false
      ttl: 4320
    mnemonic:
      name: Mnemonic
      disabled: false
      ttl: 10080
    networksdb:
      name: NetworksDB
      disabled: false
      ttl: 10080
    passivetotal:
      name: PassiveTotal
      disabled: false
      ttl: 10080
    pastebin:
      name: Pastebin
      disabled: false
      ttl: 10080
    rapiddns:
      name: RapidDNS
      disabled: false
      ttl: 4320
    recondev:
      name: ReconDev
      disabled: false
      ttl: 10080
    riddler:
      name: Riddler
      disabled: false
      ttl: 4320
    securitytrails:
      name: SecurityTrails
      disabled: false
      ttl: 1440
    shodan:
      name: Shodan
      disabled: false
      ttl: 10080
    sitedossier:
      name: SiteDossier
      disabled: false
      ttl: 4320
    sonarsearch:
      name: SonarSearch
      disabled: false
      ttl: 10080
    spyse:
      name: Spyse
      disabled: false
      ttl: 4320
    sublist3rapi:
      name: Sublist3rAPI
      disabled: false
      ttl: 4320
    threatbook: # not in account_config table yet
      name: ThreatBook
      disabled: true
      ttl: 10080
    threatcrowd:
      name: ThreatCrowd
      disabled: false
      ttl: 10080
    threatminer:
      name: ThreatMiner
      disabled: false
      ttl: 10080
    twitter:
      name: Twitter
      disabled: false
      ttl: 10080
    umbrella:
      name: Umbrella
      disabled: false
      ttl: 10080
    urlscan:
      name: URLScan
      disabled: false
      ttl: 10080
    viewdns:
      name: ViewDNS
      disabled: false
      ttl: 10080
    virustotal:
      name: VirusTotal
      disabled: false
      ttl: 10080
    wayback:
      name: Wayback
      disabled: false
      ttl: 10080
    whoisxml:
      name: WhoisXML
      disabled: false
      ttl: 10080
    yahoo:
      name: Yahoo
      disabled: true
    zetalytics:
      name: ZETAlytics
      disabled: false
      ttl: 1440
    zoomeye:
      name: ZoomEye
      disabled: false
      ttl: 1440
