---
app:
  version: 21.8.22
  # http_proxy: proxy.trivialsec.com:3128
  # https_proxy: proxy.trivialsec.com:3128
  frontend:
    asset_scheme: "https://"
    asset_domain: www.trivialsec.com
    site_scheme: "https://"
    site_domain: www.trivialsec.com
    app_scheme: "https://"
    app_domain: app.trivialsec.com
    api_scheme: "https://"
    api_domain: api.trivialsec.com
    socket_scheme: "wss://"
    socket_domain: ws.trivialsec.com
  nameservers:
    - 1.1.1.1     # Cloudflare
    - 8.8.8.8     # Google
    - 64.6.64.6   # Verisign
    - 74.82.42.42 # Hurricane Electric
    - 77.88.8.1   # Yandex.DNS
    - 9.9.9.9     # Quad9
    # - 169.254.169.253 # AWSDNS
  nmap:
    min_cvss: 0
  public_endpoints:
    - /confirmation
    - /verify
    - /login
    - /logout
    - /recovery
  require_authz:
    - /account/update-billing-email
    - /account/update-email
    - /recovery/regenerate-scratch

redis:
  host: redis
  ssl: True
  ttl: 300

mysql:
  internal_database: trivialsec
  main_user: root
  main_host: mysql-main
  replica_user: root
  replica_host: mysql-replica

aws:
  region_name: ap-southeast-2
  archive_bucket: archive-trivialsec
  public_bucket: assets-trivialsec
  env_prefix:

sendgrid:
  templates:
    invitations: d-ddd501dd76634f12bdba7dfcee416270
    registrations: d-1259c22153484803bdc4d6cb490571a6
    subscriptions: d-14c95c71ba5f40deac27eb8e0bcd0373
    updated_email: d-30f820fc0f8a4f4d9f0fd5592a7419b5
    account_recovery: d-d6ec3c4db69b46cd8a4bf873ef03bf16
    magic_link: d-c356f835c3b541d2ba76f5f50bb5a27b
    recovery_request: d-11d132b6513749a48005d21cb56df2dc
  groups:
    notifications: 14193
    focus_group: 14107
    subscriptions: 14106
    marketing: 14105
  lists:
    subscribers: a656c506-1a36-45ad-ad29-bb54db25ccd9
    members: 7c88b8a4-9b7a-4a25-9b09-be3d3a0cdcf3
    trials: 6d72d4a5-5e15-455f-9cd4-0f28a9f06e24

stripe:
  account: acct_1HTJBRGZtHTgMn6l
  products:
    enterprise:
      product_id: prod_I3YKq0kh5u21Gy
    standard:
      product_id: prod_I3QXcZm1iVM4nZ
      monthly: price_1HTJfyGZtHTgMn6lhohsngNb
      yearly: price_1HTJfzGZtHTgMn6lUTHe2gbq
    professional: 
      product_id: prod_I3Qc8SWBstGEJg
      monthly: price_1HTJkpGZtHTgMn6lgDC7UDf0
      yearly: price_1HTJkpGZtHTgMn6l1xGWhRVb
