---
version: 21.8.22
# http_proxy: proxy.trivialsec.com:3128
# https_proxy: proxy.trivialsec.com:3128
authz_expiry_seconds: 3600
session_expiry_minutes: 1440
session_cookie_name: trivialsec
queue_wait_timeout: 3
nameservers:
  - 1.1.1.1     # Cloudflare
  - 8.8.8.8     # Google
  - 64.6.64.6   # Verisign
  - 74.82.42.42 # Hurricane Electric
  - 77.88.8.1   # Yandex.DNS
  - 9.9.9.9     # Quad9
  # - 169.254.169.253 # AWSDNS

assets:
  scheme: "https://"
  host: assets.trivialsec
website:
  scheme: "https://"
  host: www.trivialsec
appserver:
  scheme: "https://"
  host: app.trivialsec
public-api:
  scheme: "https://"
  host: api.trivialsec
push:
  scheme: "wss://"
  host: push.trivialsec

nmap:
  min_cvss: 0

redis:
  host: redis
  ssl: False
  ttl: 300
  user: trivialsec

mysql:
  internal_database: trivialsec
  main_user: root
  main_host: mysql-main
  replica_user: root
  replica_host: mysql-replica

aws:
  region_name: ap-southeast-2
  archive_bucket: archive-trivialsec
  public_bucket: assets-trivialsec
  env_prefix: dev

elasticsearch:
  user: elastic
  scheme: http
  port: 9200
  hosts:
    - elasticsearch

sendgrid:
  templates:
    invitations: d-ddd501dd76634f12bdba7dfcee416270
    registrations: d-1259c22153484803bdc4d6cb490571a6
    subscriptions: d-14c95c71ba5f40deac27eb8e0bcd0373
    updated_email: d-30f820fc0f8a4f4d9f0fd5592a7419b5
    account_recovery: d-a791985ca56f4339acd9a77cc5d66cbd
    magic_link: d-c356f835c3b541d2ba76f5f50bb5a27b
    recovery_request: d-11d132b6513749a48005d21cb56df2dc
  groups:
    notifications: 14193
    focus_group: 14107
    subscriptions: 14106
    marketing: 14105
  lists:
    subscribers: a656c506-1a36-45ad-ad29-bb54db25ccd9
    members: 7c88b8a4-9b7a-4a25-9b09-be3d3a0cdcf3
    trials: 6d72d4a5-5e15-455f-9cd4-0f28a9f06e24

stripe:
  account: acct_1HTJBRGZtHTgMn6l
  products:
    trial:
      product_id: prod_KrarSMRWwK5WWb
    enterprise:
      product_id: prod_I3nN4WJDEcSqKw
    standard:
      product_id: prod_I3nOpBV12MdUpr
      monthly: price_1KBs2lGZtHTgMn6lIB23EJwF
      yearly: price_1KBs2lGZtHTgMn6lCsr2EozM
    professional: 
      product_id: prod_I3nPIEoht0v7Tf
      monthly: price_1KBs2lGZtHTgMn6l6K2juj8C
      yearly: price_1KBs2lGZtHTgMn6lR5t3KJX4
