AWSTemplateFormatVersion: '2010-09-09'

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "App Configuration"
        Parameters:
          - OwnerEmail
          - Environment
          - Purpose
      - Label:
          default: "Stack Configuration"
        Parameters:
          - UserName
    ParameterLabels:
      OwnerEmail:
        default: "Who to notify or contact for stach changes?"
      Purpose:
        default: "What is the use case? to determine if the stack will persist"

Parameters:
  OwnerEmail:
    Type: String
  Environment:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
  Purpose:
    Type: String
    Default: Testing
    AllowedValues:
      - Testing
      - Deploy
      - External
  UserName:
    Type: String
  BucketName:
    Type: String
  IndexDocument:
    Type: String
    Default: index.html
  ErrorDocument:
    Type: String
    Default: error.html
  QueueName:
    Type: String
  MessageRetentionPeriod:
    Type: Number
  VisibilityTimeout:
    Type: Number
  MaxReceiveCount:
    Type: Number

Resources:
  PythonBase:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: trivialsec/python-base
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

  NodeBase:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: trivialsec/node-base
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

  Web:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: trivialsec/web
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

  Sockets:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: trivialsec/sockets
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload

  Workers:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: trivialsec/workers
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
