AWSTemplateFormatVersion: '2010-09-09'

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "App Configuration"
        Parameters:
          - OwnerEmail
          - Environment
          - Purpose
      - Label:
          default: "Stack Configuration"
        Parameters:
          - BucketName
          - IndexDocument
          - ErrorDocument
    ParameterLabels:
      OwnerEmail:
        default: "Who to notify or contact for stach changes?"
      Purpose:
        default: "What is the use case? to determine if the stack will persist"

Parameters:
  OwnerEmail:
    Type: String
  Environment:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
  Purpose:
    Type: String
    Default: Testing
    AllowedValues:
      - Testing
      - Deploy
      - External
  UserName:
    Type: String
  BucketName:
    Type: String
  IndexDocument:
    Type: String
    Default: index.html
  ErrorDocument:
    Type: String
    Default: error.html

Resources:
  EncryptedS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  S3BucketSecureURL:
    Value: !Ref EncryptedS3Bucket
