AWSTemplateFormatVersion: 2010-09-09

Parameters:
    HostedZoneName:
      Type: String
      Default: trivialsec.com.
    TrivialsecVerification:
      Type: String
      Default: oajrzBUbE42xvAi07CTLljRSiQTNdzR9OHhzB5zLXiA
    ProtonmailDomainkey:
      Type: String
      Default: dwpdkrbnojqkv3vv5ugaybesokkv6qo25yswqpd3sphzabe3i5yza

Resources:
  dnstrivialseccom:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Ref HostedZoneName
          Type: TXT
          TTL: '300'
          ResourceRecords:
            - '"v=spf1 include:_spf.protonmail.ch mx ~all"'
            - '"protonmail-verification=78c74c851e6fd181f96fe6994e6e325672365710"'
            - !Sub
                - '"trivialsec=${TrivialsecVerification}"'
                - TrivialsecVerification: !Ref TrivialsecVerification
  dnsdmarctrivialseccom:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Sub
            - "_dmarc.${HostedZoneName}"
            - HostedZoneName: !Ref HostedZoneName
          Type: TXT
          TTL: '300'
          ResourceRecords:
            - '"v=DMARC1; p=none; rua=mailto:chris@langton.cloud"'
  dnsprotonmaildomainkeytrivialseccom:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Sub
            - "protonmail._domainkey.${HostedZoneName}"
            - HostedZoneName: !Ref HostedZoneName
          Type: CNAME
          TTL: '300'
          ResourceRecords:
            - !Sub
                - "protonmail.domainkey.${ProtonmailDomainkey}.domains.proton.ch."
                - ProtonmailDomainkey: !Ref ProtonmailDomainkey
  dnsprotonmail2domainkeytrivialseccom:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Sub
            - "protonmail2._domainkey.${HostedZoneName}"
            - HostedZoneName: !Ref HostedZoneName
          Type: CNAME
          TTL: '300'
          ResourceRecords:
            - !Sub
                - "protonmail2.domainkey.${ProtonmailDomainkey}.domains.proton.ch."
                - ProtonmailDomainkey: !Ref ProtonmailDomainkey
  dnsprotonmail3domainkeytrivialseccom:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Sub
            - "protonmail3._domainkey.${HostedZoneName}"
            - HostedZoneName: !Ref HostedZoneName
          Type: CNAME
          TTL: '300'
          ResourceRecords:
            - !Sub
                - "protonmail3.domainkey.${ProtonmailDomainkey}.domains.proton.ch."
                - ProtonmailDomainkey: !Ref ProtonmailDomainkey
  dnswstrivialseccom:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Sub
            - "ws.${HostedZoneName}"
            - HostedZoneName: !Ref HostedZoneName
          Type: TXT
          TTL: '300'
          ResourceRecords:
            - !Sub
                - '"trivialsec=${TrivialsecVerification}"'
                - TrivialsecVerification: !Ref TrivialsecVerification
  dnswwwtrivialseccom:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
        - Name: !Sub
            - "www.${HostedZoneName}"
            - HostedZoneName: !Ref HostedZoneName
          Type: TXT
          TTL: '300'
          ResourceRecords:
            - !Sub
                - '"trivialsec=${TrivialsecVerification}"'
                - TrivialsecVerification: !Ref TrivialsecVerification
