AWSTemplateFormatVersion: '2010-09-09'

Metadata: 
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "App Configuration"
        Parameters:
          - Environment
          - Purpose
          - AppName
      - Label:
          default: "Stack Configuration"
        Parameters:
          - MysqlPassword
          - SessionSecretKey
          - RecaptchaSiteKey
          - RecaptchaSecretKey
          - SendGridApiKey
          - StripePublishableKey
          - StripeSecretKey
          - StripeWebhookSecret
          - GoogleAPIKey
          - PhishtankKey
          - PhishtankUsername
          - HoneyScoreKey
          - ProjectHoneypot
    ParameterLabels:
      Purpose:
        default: "What is the use case? to determine if the stack will persist"
      RecaptchaSiteKey:
        default: "Create your own reCAPTCHA v3 site and keys here: https://www.google.com/recaptcha/admin/create"
      MysqlPassword:
        default: "Generate a password for your mysql instance and store it here"

Parameters:
  AppName:
    Type: String
    Default: 'trivialsec'
  Environment:
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
  Purpose:
    Type: String
    Default: Testing
    AllowedValues:
      - Testing
      - Deploy
      - External
  MysqlPassword:
    Type: String
    NoEcho: true
  RecaptchaSecretKey:
    Type: String
    NoEcho: true
  SessionSecretKey:
    Type: String
  RecaptchaSiteKey:
    Type: String
  SendGridApiKey:
    Type: String
    NoEcho: true
  StripePublishableKey:
    Type: String
  StripeSecretKey:
    Type: String
    NoEcho: true
  StripeWebhookSecret:
    Type: String
  GoogleAPIKey:
    Type: String
    NoEcho: true
  PhishtankKey:
    Type: String
    NoEcho: true
  PhishtankUsername:
    Type: String
  HoneyScoreKey:
    Type: String
    NoEcho: true
  ProjectHoneypot:
    Type: String
    NoEcho: true

Resources:
  ParameterRecaptchaSecretKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/RecaptchaSecretKey"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref RecaptchaSecretKey

  ParameterRecaptchaSiteKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/RecaptchaSiteKey"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref RecaptchaSiteKey

  ParameterMysqlPassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/MysqlPassword"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref MysqlPassword

  ParameterSessionSecretKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/SessionSecretKey"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref SessionSecretKey

  ParameterSendGridApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/SendGridApiKey"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref SendGridApiKey

  ParameterStripePublishableKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/StripePublishableKey"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref StripePublishableKey

  ParameterStripeSecretKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/StripeSecretKey"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref StripeSecretKey

  ParameterStripeWebhookSecret:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/StripeWebhookSecret"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref StripeWebhookSecret

  ParameterGoogleAPIKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/GoogleAPIKey"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref GoogleAPIKey

  ParameterPhishtankKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/PhishtankKey"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref PhishtankKey

  ParameterPhishtankUsername:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/PhishtankUsername"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref PhishtankUsername

  ParameterHoneyScoreKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/HoneyScoreKey"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref HoneyScoreKey

  ParameterProjectHoneypot:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub
        - "/${Environment}/${Purpose}/${AppName}/ProjectHoneypot"
        - Environment: !Ref Environment
          Purpose: !Ref Purpose
          AppName: !Ref AppName
      Type: String
      Value: !Ref ProjectHoneypot
